import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import styles from "./page.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <div
        style={{
          display: "flex",
          flexDirection: "row",
          justifyContent: "space-around",
        }}
      >
        <Link
          className={styles.Link}
          passHref
          href="/salaryDefinition/salaryDefinition"
        >
          <div className={styles.navLink}>Salary Breakdowns</div>
        </Link>
        <Link
          className={styles.Link}
          passHref
          href="/salaryDefinition/taxDefinition"
        >
          <div className={styles.navLink}>Tax Definitions</div>
        </Link>
        <Link className={styles.Link} passHref href="/salaryDefinition/payslip">
          <div className={styles.navLink}>Payslips</div>
        </Link>
      </div>
      <div className={inter.className}>{children}</div>
    </div>
  );
}
