import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <div>
        <Link href="/salaryDefinition/salaryDefinition" style={{margin: "10px", textDecoration: 'none'}}>Go to salaryDefinition</Link>
        <Link href="/salaryDefinition/taxDefinition" style={{margin: "10px", textDecoration: 'none'}}>Go to taxDefinition</Link>
        <Link href="/salaryDefinition/payslip" style={{margin: "10px", textDecoration: 'none'}}>Go to payslip</Link>
      </div>
      <div className={inter.className}>{children}</div>
    </div>
  );
}
