import type { Metadata } from "next";
import { Inter } from "next/font/google";
import CustomBox from "../components/CustomBox";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  graphics,
  grossSalary,
  netSalary,
  table,
  totalLoan,
  totalTax,
}: Readonly<{
  children: React.ReactNode;
  graphics: React.ReactNode;
  grossSalary: React.ReactNode;
  netSalary: React.ReactNode;
  table: React.ReactNode;
  totalLoan: React.ReactNode;
  totalTax: React.ReactNode;
}>) {
  return (
    <div>
      <div style={{ display: "flex", flexDirection: "row" }}>
        <div style={{ display: "flex", flexDirection: "column" }}>
          <div style={{ display: "flex", flexDirection: "row" }}>
            <CustomBox>{grossSalary}</CustomBox>
            <CustomBox>{netSalary}</CustomBox>
          </div>
          <div style={{ display: "flex", flexDirection: "row" }}>
            <CustomBox>{totalLoan}</CustomBox>
            <CustomBox>{totalTax}</CustomBox>
          </div>
        </div>
        <div>
          <CustomBox>{graphics}</CustomBox>
        </div>
      </div>
      <CustomBox>{table}</CustomBox>
      <div className={inter.className}>{children}</div>
    </div>
  );
}
