import type { Metadata } from "next";
import { Inter } from "next/font/google";
import CustomBox from "../components/CustomBox";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  amountUsed,
  budgetUsed,
  totalBalance,
  totalBudget,
  table,
}: Readonly<{
  children: React.ReactNode;
  amountUsed: React.ReactNode;
  budgetUsed: React.ReactNode;
  totalBalance: React.ReactNode;
  totalBudget: React.ReactNode;
  table: React.ReactNode;
}>) {
  return (
    <div>
      <div style={{ display: "flex", flexDirection: "row" }}>
        <CustomBox>{totalBudget}</CustomBox>
        <CustomBox>{amountUsed}</CustomBox>
        <CustomBox>{totalBalance}</CustomBox>
        <CustomBox>{budgetUsed}</CustomBox>
      </div>
      <CustomBox>{table}</CustomBox>
      <div className={inter.className}>{children}</div>
    </div>
  );
}
